# Generated by Django 4.1.1 on 2022-10-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_photo",
                    models.FileField(blank=True, max_length=30, upload_to=""),
                ),
                ("client_name", models.CharField(max_length=50)),
                ("client_neckname", models.CharField(default="", max_length=50)),
                ("client_phone", models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
