# Generated by Django 4.1.1 on 2022-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_client_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_neckname",
            field=models.CharField(
                default="C:/my_files/projects/PYTHON/django_projects/MyApp/first_app/static/images/user.png",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_photo",
            field=models.FileField(default="", max_length=30, upload_to=""),
        ),
    ]
