# Generated by Django 4.1.1 on 2022-10-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0003_alter_client_client_neckname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_neckname",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_photo",
            field=models.FileField(
                default="C:/my_files/projects/PYTHON/django_projects/MyApp/first_app/static/images/user.png",
                max_length=30,
                upload_to="",
            ),
        ),
    ]
