# Generated by Django 4.1.1 on 2022-10-23 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0004_alter_client_client_neckname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_last_payment",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client",
            name="client_last_payment_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="client_total",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_photo",
            field=models.ImageField(
                default="C:/my_files/projects/PYTHON/django_projects/MyApp/first_app/static/images/user.png",
                max_length=50,
                upload_to="static/images/",
            ),
        ),
    ]
