# Generated by Django 4.1.1 on 2022-10-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0005_client_client_last_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
