# Generated by Django 4.1.1 on 2022-10-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0007_alter_client_client_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_photo",
            field=models.ImageField(
                default="C:/my_files/projects/PYTHON/django_projects/MyApp/first_app/static/images/user.png",
                max_length=50,
                upload_to="users",
            ),
        ),
    ]
