# Generated by Django 4.1.1 on 2022-10-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0008_alter_client_client_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_neckname",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_photo",
            field=models.ImageField(max_length=50, upload_to="users"),
        ),
    ]
