# Generated by Django 4.1.1 on 2022-10-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0010_alter_client_client_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_photo",
            field=models.ImageField(upload_to="users/"),
        ),
    ]
