# Generated by Django 4.1.1 on 2022-10-28 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0011_alter_client_client_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_last_operation",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
